export const USER_SIGN_IN_API = "USER_SIGN_IN_API";
export const GET_ALL_PROJECT_CATEGORY_API = " GET_ALL_PROJECT_CATEGORY_API";
export const GET_ALL_PROJECT_CATEGORY = " GET_ALL_PROJECT_CATEGORY";
export const CREATE_PROJECT_API = "CREATE_PROJECT_API";
export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const GET_ALL_PROJECTS_API = "GET_ALL_PROJECTS_API";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_API = "DELETE_PROJECT_API";
